# Generated by Django 5.0.7 on 2024-07-11 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
        ('subject', '0002_subjecttotaught_allocatedsubject_potentialsubject'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletedSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject.subject')),
            ],
            options={
                'unique_together': {('student', 'subject')},
            },
        ),
    ]
