# Generated by Django 5.0.7 on 2024-07-13 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_completedsubject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
    ]
