# Generated by Django 5.0.7 on 2024-08-15 10:53

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_uploadstudent'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='completed_subjects',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, help_text='List of completed subject IDs', size=None),
        ),
    ]
