# Generated by Django 5.0.7 on 2024-08-17 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_alter_student_dob_alter_student_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completedsubject',
            name='completion_date',
        ),
    ]
