# Generated by Django 5.0.7 on 2024-08-17 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0003_newpotentialsubject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='credits',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='department',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
